groups:
- name: task
  rules:

  - alert: task_high_cpu_usage_50
    expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~".+"}[1m])) by (container_label_com_docker_swarm_task_name,container_label_com_docker_swarm_node_id) * 100 > 50
    for: 1m
    annotations:
      summary: "CPU hive task on '{{ $labels.container_label_com_docker_swarm_node_id }}'"
      description: "Usage of {{ $labels.container_label_com_docker_swarm_task_name }} is at {{ humanize $value}}%."

  - alert: task_high_memory_usage_70
    expr: sum(rate(container_memory_rss{container_label_com_docker_swarm_task_name=~".+"}[1m])) by (container_label_com_docker_swarm_task_name,container_label_com_docker_swarm_node_id) * 100 > 0
    for: 1m
    annotations:
      summary: "Memory hive task on '{{ $labels.container_label_com_docker_swarm_node_id }}'"
      description: "Usage of {{ $labels.container_label_com_docker_swarm_task_name }} is {{ humanize $value}}% {{ $value }}."
