global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  repeat_interval: 15m
  group_interval: 5m
  group_wait: 1m
  routes:
  - receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/{{SLACK_KEY}}'
        username: '{{SLACK_USERNAME}}'
        channel: '{{SLACK_CHANNEL}}'
        text: '{{ .CommonAnnotations.summary }} ---> {{ .CommonAnnotations.description }}'
        icon_emoji: ':dart:'