global:
  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: slack_receiver

receivers:
  - name: slack_receiver
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/{{SLACK_KEY}}'
      username: '{{SLACK_USERNAME}}'
      channel: '{{SLACK_CHANNEL}}'
      # send_resolved: true # This is nice but sends too many notifications
      text: '{{ .CommonAnnotations.summary }}: {{ .CommonAnnotations.description }}'
