global:
  scrape_interval:     5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'Prometheus-Monitor'
  
rule_files:
  - '/etc/prometheus-rules/alerts.nodes'
  - '/etc/prometheus-rules/alerts.task'

scrape_configs:
  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'exporter'
    dns_sd_configs:
    - names:
      - 'tasks.exporter'
      type: 'A'
      port: 9100

  - job_name: 'alertmanager'
    dns_sd_configs:
    - names:
      - 'tasks.alertmanager'
      type: 'A'
      port: 9093

