#!/usr/bin/env bash

export SWARM_HOST_IP="{{HOST_IP}}"

export SWARM_ADMIN_USER="{{ADMIN_USER}}"
export SWARM_ADMIN_PASSWORD="{{ADMIN_PASSWORD}}"

export SWARM_SLACK_KEY="{{SLACK_KEY}}"
export SWARM_SLACK_CHANNEL="{{SLACK_CHANNEL}}"
export SWARM_SLACK_USERNAME="{{SLACK_USERNAME}}"

